version: 2.1
jobs:
  mrom-X00TD:
   docker:
      - image: iatrpkd/docker:Twrp-build
   steps:
      - run:
          name: Install Packages
          no_output_timeout: 20m
          command: |
            sudo apt install -y gcc-arm-linux-gnueabi g++-arm-linux-gnueabi
            sudo apt install python3 python3.6 bison repo libssl-dev build-essential curl flex git gnupg gperf liblz4-tool libncurses5-dev libsdl1.2-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev build-essential kernel-package libncurses5-dev bzip2 git python sudo gcc g++ openssh-server tar gzip ca-certificates -y
            sudo apt install ccache curl flex  git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev -y
            sudo apt install curl gnupg gperf libsdl1.2-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools zip zlib1g-dev g++-multilib lib32ncurses5-dev -y
            #sudo apt install android-tools-adbd androidsdk-ddms android-tools-fastboot -y
            sudo apt install -y git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc repo nano
            sudo apt install -y git gnupg flex bison gperf build-essential zip curl zlib1g-dev x11proto-core-dev libx11-dev libgl1-mesa-dev libxml2-utils xsltproc unzip repo nano libssl-dev
            sudo apt install -y bison curl flex g++-multilib gnupg gperf imagemagick lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zip zlib1g-dev
      - run:
          name: Syncing source
          no_output_timeout: 20m
          command: |
            cd ~
            mkdir mrom && cd mrom
            repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-9.0
            repo sync --fetch-submodules
            rm -rf ~/mrom/bootable/recovery
            git clone -b mr-9.0 https://github.com/KernelPanic-OpenSource/bootable_recovery ~/mrom/bootable/recovery
            rm -rf ~/mrom/system/extras/multirom
            git clone -b master https://github.com/multirom-klte/multirom system/extras/multirom
            rm -rf ~/mrom/system/extras/multirom/adbd
            git clone -b mr-9.0 https://github.com/KernelPanic-OpenSource/system_extras_multirom_adbd system/extras/multirom/adbd
            cd ~/mrom/system/extras/multirom
            git submodule update --init
            cd ~/mrom && rm -rf system/extras/libbootimg
            git clone https://github.com/multirom-klte/libbootimg ~/mrom/system/extras/libbootimg
            mkdir -p device/asus && cd device/asus
            git clone -b multirom https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME ASUS_X00TD
            cd ~/mrom && mkdir -p kernel/asus && cd kernel/asus
            git clone -b lineage-16.0 https://github.com/iatrz/android_kernel_asus_sdm660 ASUS_X00TD --depth=1
      - run:
          name: Building
          no_output_timeout: 20m
          command: |
            cd ~/mrom
            export ALLOW_MISSING_DEPENDENCIES=true
            export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
            source build/envsetup.sh
            lunch omni_ASUS_X00TD-eng
            mka -j$(nproc --all) recoveryimage
            mka -j$(nproc --all) multirom
            mka -j$(nproc --all) multirom_zip
            mka -j$(nproc --all) multirom_uninstaller
      - run:
          name: Telegram Upload CI
          no_output_timeout: 20m
          command: |
            cd ~/mrom/out/target/product/ASUS_X00TD
            ZIPNAME="mrom-$(date +%d_%m_%Y_%H_%M)-X00TD.zip"
            sudo zip -r9 $ZIPNAME recovery.img multirom.zip multirom_uninstaller.zip
            curl -F chat_id=$CHAT_ID -F document=@$ZIPNAME -F parse_mode=markdown https://api.telegram.org/bot$BOT_TOKEN/sendDocument
workflows:
  version: 2.1
  cooking:
    jobs:
      - mrom-X00TD
