version: 2.1
jobs:
  mrom-X00TD:
   docker:
      - image: iatrpkd/docker:Twrp-build
   steps:
      - run:
          name: Syncing source
          no_output_timeout: 20m
          command: |
            cd ~
            mkdir mrom && cd mrom
            repo init --depth=1 -u git://github.com/Linux-On-Sdm6Series/android.git -b multirom
            repo sync --fetch-submodules
            rm -rf ~/mrom/bootable/recovery
            git clone -b mr-9.0 https://github.com/KernelPanic-OpenSource/bootable_recovery ~/mrom/bootable/recovery
            rm -rf ~/mrom/system/extras/multirom
            git clone -b master https://github.com/multirom-klte/multirom system/extras/multirom
            rm -rf ~/mrom/system/extras/multirom/adbd
            git clone -b mr-9.0 https://github.com/KernelPanic-OpenSource/system_extras_multirom_adbd system/extras/multirom/adbd
            cd ~/mrom/system/extras/multirom
            git submodule update --init
            cd ~/mrom && rm -rf system/extras/libbootimg
            git clone https://github.com/multirom-klte/libbootimg ~/mrom/system/extras/libbootimg
            mkdir -p device/asus && cd device/asus
            git clone -b multirom https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME ASUS_X00TD
            cd ~/mrom && mkdir -p kernel/asus && cd kernel/asus
            git clone -b lineage-16.0 https://github.com/iatrz/android_kernel_asus_sdm660 ASUS_X00TD --depth=1
      - run:
          name: Install Packages
          no_output_timeout: 20m
          command: |
            sudo apt install -y gcc-arm-linux-gnueabi g++-arm-linux-gnueabi
      - run:
          name: Building
          no_output_timeout: 20m
          command: |
            cd ~/mrom
            export ALLOW_MISSING_DEPENDENCIES=true
            export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
            source build/envsetup.sh
            lunch omni_ASUS_X00TD-eng
            mka -j$(nproc --all) recoveryimage
            mka -j$(nproc --all) multirom trampoline
            mka -j$(nproc --all) multirom_zip
            mka -j$(nproc --all) multirom_uninstaller
      - run:
          name: Telegram Upload CI
          no_output_timeout: 20m
          command: |
            cd ~/mrom/out/target/product/ASUS_X00TD
            ZIPNAME="mrom-$(date +%d_%m_%Y_%H_%M)-X00TD.zip"
            sudo zip -r9 $ZIPNAME recovery.img multirom.zip multirom_uninstaller.zip
            curl -F chat_id=$CHAT_ID -F document=@$ZIPNAME -F parse_mode=markdown https://api.telegram.org/bot$BOT_TOKEN/sendDocument
workflows:
  version: 2.1
  cooking:
    jobs:
      - mrom-X00TD
