version: 2.1
jobs:
  mrom-X00TD:
   docker:
      - image: iatrpkd/docker:Twrp-build
   steps:
      - run:
          name: Syncing source
          no_output_timeout: 20m
          command: |
            cd ~
            mkdir mrom && cd mrom
            repo init --depth=1 -u https://github.com/multirom-dev/android -b android-7.1
            repo sync  --force-sync --current-branch --no-tags --no-clone-bundle --optimized-fetch --prune -j$(nproc --all)
            mkdir -p device/asus && cd device/asus
            git clone -b multirom https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME ASUS_X00TD
      - run:
          name: Building
          no_output_timeout: 20m
          command: |
            cd ~/mrom
            rm -rf vendor/qcom/opensource/cryptfs_hw
            source build/envsetup.sh
            export ALLOW_MISSING_DEPENDENCIES=true
            lunch omni_ASUS_X00TD-eng
            mka -j$(nproc --all) recoveryimage
            mka -j$(nproc --all) multirom_zip
            mka -j$(nproc --all) multirom_uninstaller
      - run:
          name: Telegram Upload CI
          no_output_timeout: 20m
          command: |
            cd ~/mrom/out/target/product/ASUS_X00TD
            ZIPNAME="mrom-$(date +%d_%m_%Y_%H_%M)-X00TD.zip"
            sudo zip -r9 $ZIPNAME *.zip
            curl -F chat_id=$CHAT_ID -F document=@$ZIPNAME -F parse_mode=markdown https://api.telegram.org/bot$BOT_TOKEN/sendDocument
workflows:
  version: 2.1
  cooking:
    jobs:
      - mrom-X00TD
